POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Sergio", 
   "email": "sergio@gmail.com",
   "password": "123456",
   "role": "ADMIN"   
}

###
POST http://localhost:3003/login
Content-Type: application/json

{   
   "email": "jaime@gmail.com",
   "password": "123456"
}

